version: '2'
services:
    booterapplication-app:
        image: booterapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://booterapplication-mysql:3306/booterapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=booterapplication-elasticsearch:9300
        ports:
            - 8080:8080
    booterapplication-mysql:
        extends:
            file: mysql.yml
            service: booterapplication-mysql
    booterapplication-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: booterapplication-elasticsearch
